title: jekyll-rtd-theme
description: Opinionated standard documentation theme, with few options, but everything!

theme: null

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://PPTaa.github.io/" # the base hostname & protocol for your site

